import dayjs from "dayjs";
import * as XLSX from "xlsx";
import { message } from "antd";

// Helper function to format dates
const formatDate = (date) => {
  if (!date) return "N/A";
  try {
    return dayjs(date).format("YYYY-MM-DD HH:mm:ss");
  } catch {
    return "N/A";
  }
};

// Helper function to format date only
const formatDateOnly = (date) => {
  if (!date) return "N/A";
  try {
    return dayjs(date).format("YYYY-MM-DD");
  } catch {
    return "N/A";
  }
};

// Helper function to get safe number
const getSafeNumber = (value) => {
  if (value === null || value === undefined || value === "null" || value === "undefined") {
    return 0;
  }
  const num = Number(value);
  return isNaN(num) ? 0 : num;
};

// Helper function to calculate percentage
const calculatePercentage = (part, total) => {
  if (!total || total === 0) return 0;
  return Math.round((part / total) * 100 * 100) / 100; // Round to 2 decimal places
};

// Helper function to get candidate metrics for a work order
const getWOCandidateMetrics = (woId, woTitle, filteredData) => {
  const woSummary = filteredData?.hoverData?.activeWOSummary?.find(
    wo => (wo.woId === woId) || (wo.woName === woTitle)
  );
  if (woSummary) {
    return {
      required: woSummary.totalCandidatesReq || 0,
      hired: woSummary.hired || 0,
      inPipeline: woSummary.staged || 0,
      pending: woSummary.pending || 0,
      completionRate: calculatePercentage(woSummary.hired || 0, woSummary.totalCandidatesReq || 0),
    };
  }
  const wo = filteredData?.workOrders?.find(w => w.id === woId);
  const required = wo?.numberOfCandidate || 0;
  return {
    required,
    hired: 0,
    inPipeline: 0,
    pending: required,
    completionRate: 0,
  };
};

export const handleExportExcel = (filteredData, filters, filterOptions, data = null) => {
  if (!filteredData) {
    message.warning("No data available to export");
    return;
  }

  try {
    const workbook = XLSX.utils.book_new();

    // ==================== SHEET 1: EXECUTIVE SUMMARY ====================
    const summaryData = [
      ["ADMIN DASHBOARD - EXECUTIVE SUMMARY"],
      ["Report Generated:", dayjs().format("YYYY-MM-DD HH:mm:ss")],
      ["Generated By:", "Admin Dashboard"],
      [],
      ["FILTERS APPLIED"],
      ["Client(s):", filters.clientId?.length > 0 
        ? filterOptions?.clients?.filter(c => filters.clientId.includes(c.id)).map(c => c.name).join(", ") 
        : "All Clients"],
      ["Project(s):", filters.projectId?.length > 0 
        ? filterOptions?.projects?.filter(p => filters.projectId.includes(p.id)).map(p => p.name).join(", ") 
        : "All Projects"],
      ["Work Order:", filters.workOrderId !== "all" 
        ? (filterOptions?.workOrders?.find(wo => wo.id === filters.workOrderId)?.name || "N/A") 
        : "All Work Orders"],
      ["Reference Code:", filters.referenceCode !== "all" 
        ? (filterOptions?.referenceCodes?.find(ref => ref.id === filters.referenceCode)?.name || "N/A") 
        : "All Reference Codes"],
      ["Date Range:", filters.startDate && filters.endDate 
        ? `${formatDateOnly(filters.startDate)} to ${formatDateOnly(filters.endDate)}` 
        : "All Dates"],
      ["Deadline Period:", filters.deadlinePeriod ? `${filters.deadlinePeriod} Days` : "N/A"],
      ["Completion Percentage:", filters.completionPercentage || "N/A"],
      ["KPIs/Achievements Date Range:", filters.dateRange ? `Past ${filters.dateRange} Days` : "N/A"],
      [],
      ["KEY METRICS"],
      ["Total Clients", getSafeNumber(filteredData?.statistics?.totalClients)],
      ["Total Projects", getSafeNumber(filteredData?.statistics?.totalProjects)],
      ["Active Work Orders", getSafeNumber(filteredData?.statistics?.activeWorkOrders)],
      ["Inactive Work Orders", Math.max(0, getSafeNumber(filteredData?.statistics?.totalWorkOrders) - getSafeNumber(filteredData?.statistics?.activeWorkOrders))],
      ["Total Work Orders", getSafeNumber(filteredData?.statistics?.totalWorkOrders)],
      ["Active Requisitions", getSafeNumber(filteredData?.statistics?.activeRequisitions)],
      ["Total Candidates Needed", getSafeNumber(filteredData?.statistics?.totalCandidatesNeeded)],
      ["Total Candidates in Pipeline", getSafeNumber(filteredData?.statistics?.totalCandidatesInPipeline)],
      ["Total Hired/Converted", getSafeNumber(filteredData?.statistics?.totalHired)],
      ["Pending Requirements", getSafeNumber(filteredData?.statistics?.pendingRequirements)],
      ["Pipeline Fill Rate (%)", calculatePercentage(
        getSafeNumber(filteredData?.statistics?.totalCandidatesInPipeline),
        getSafeNumber(filteredData?.statistics?.totalCandidatesNeeded)
      )],
      ["Hiring Success Rate (%)", calculatePercentage(
        getSafeNumber(filteredData?.statistics?.totalHired),
        getSafeNumber(filteredData?.statistics?.totalCandidatesNeeded)
      )],
      [],
      ["KEY PERFORMANCE INDICATORS (KPIs)"],
      ["Time to Hire (days)", getSafeNumber(filteredData?.kpis?.timeToHire)],
      ["Average Time in Pipeline (days)", getSafeNumber(filteredData?.kpis?.averageTimeInPipeline)],
      ["Offer Acceptance Rate (%)", getSafeNumber(filteredData?.kpis?.offerAcceptanceRate)],
      ["WO Pipeline Completion Rate (%)", getSafeNumber(filteredData?.kpis?.woPipelineCompletionRate)],
      ["WO Completion Rate (%)", getSafeNumber(filteredData?.kpis?.woCompletionRate)],
      [],
      ["ACHIEVEMENTS (Past " + (filters.dateRange || 7) + " Days)"],
      ["New CVs Added", getSafeNumber(filteredData?.achievements?.newCVsAdded)],
      ["New Candidates Added", getSafeNumber(filteredData?.achievements?.newCandidatesAdded)],
      ["Completed Work Orders", getSafeNumber(filteredData?.achievements?.completedWOs)],
      ["Interviews Conducted", getSafeNumber(filteredData?.achievements?.interviewsConducted)],
      ["Converted to Employee", getSafeNumber(filteredData?.achievements?.convertedToEmployee)],
    ];

    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    
    // Set column widths for summary sheet
    summarySheet["!cols"] = [
      { wch: 30 }, // Column A
      { wch: 40 }, // Column B
    ];
    
    XLSX.utils.book_append_sheet(workbook, summarySheet, "Executive Summary");

    // ==================== SHEET 2: DETAILED WORK ORDERS ====================
    if (filteredData?.workOrders?.length > 0) {
      // Helper function to format status name
      const formatStatusName = (status) => {
        return status
          .split("_")
          .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
          .join(" ");
      };

      // Get all unique statuses from applicationStatusData if available
      const allStatuses = new Set();
      if (filteredData?.applicationStatusData && Array.isArray(filteredData.applicationStatusData)) {
        filteredData.applicationStatusData.forEach((item) => {
          if (item.status) {
            allStatuses.add(item.status);
          }
        });
      }
      
      // Add common statuses even if not in data
      const commonStatuses = [
        "sourced", "selected", "applied", "rejected", "screening", 
        "pipeline", "interview", "offer", "offer_pending", "offer_revised",
        "in-pending", "approved", "hired", "completed"
      ];
      commonStatuses.forEach(status => allStatuses.add(status));

      const workOrderData = filteredData.workOrders.map((wo) => {
        const metrics = getWOCandidateMetrics(wo.id, wo.title, filteredData);
        const daysUntilDeadline = wo.deadlineDate 
          ? dayjs(wo.deadlineDate).diff(dayjs(), "days")
          : null;
        const isOverdue = daysUntilDeadline !== null && daysUntilDeadline < 0;
        
        // Base row data
        const rowData = {
          "Work Order ID": wo.id || "N/A",
          "Work Order Title": wo.title || "N/A",
          "Job Code": wo.jobCode || "N/A",
          "Requisition No": wo.requisitionNo || "N/A",
          "Reference No": wo.referenceNo || "N/A",
          "Client Name": wo.client?.name || "N/A",
          "Client ID": wo.client?.id || "N/A",
          "Project Name": wo.project?.name || "N/A",
          "Project ID": wo.project?.id || "N/A",
          "Status": wo.isActive === "active" ? "Active" : "Inactive",
          "Priority": wo.priority || "N/A",
          "Created Date": formatDateOnly(wo.createdAt),
          "Deadline Date": formatDateOnly(wo.deadlineDate),
          "Days Until Deadline": daysUntilDeadline !== null ? daysUntilDeadline : "N/A",
          "Is Overdue": isOverdue ? "Yes" : "No",
          "Candidates Required": metrics.required,
          "Total Candidates": metrics.hired + metrics.inPipeline + metrics.pending,
          "Candidates Hired": metrics.hired,
          "Candidates In Pipeline": metrics.inPipeline,
          "Candidates Pending": metrics.pending,
          "Completion Rate (%)": metrics.completionRate,
          "Remaining Candidates": metrics.required - metrics.hired,
        };

        // Add all status columns (will be 0 if not available in current data structure)
        // This ensures consistency with AdminDashboardDetail export
        Array.from(allStatuses).sort().forEach((status) => {
          const statusKey = formatStatusName(status);
          // Try to get status count from applicationStatusData if available
          // For now, set to 0 as the detailed breakdown isn't available in main dashboard data
          // This structure allows for future enhancement when backend provides status breakdown
          rowData[statusKey] = 0;
        });

        return rowData;
      });

      const workOrderSheet = XLSX.utils.json_to_sheet(workOrderData);
      
      // Calculate column widths dynamically
      const maxWidths = {};
      workOrderData.forEach((row) => {
        Object.keys(row).forEach((key) => {
          const cellValue = String(row[key] || "");
          maxWidths[key] = Math.max(maxWidths[key] || 10, cellValue.length, key.length);
        });
      });
      
      workOrderSheet["!cols"] = Object.keys(workOrderData[0] || {}).map((key) => ({
        wch: Math.min(Math.max(maxWidths[key] || 10, 10), 30),
      }));
      
      XLSX.utils.book_append_sheet(workbook, workOrderSheet, "Work Orders");
    }

    // ==================== SHEET 3: CLIENT SUMMARY (DETAILED) ====================
    if (filteredData?.hoverData?.clientSummary?.length > 0) {
      const clientSummaryData = filteredData.hoverData.clientSummary.map((client) => ({
        "Client Name": client.clientName || "N/A",
        "Total Work Orders": getSafeNumber(client.totalWorkOrders),
        "Active Work Orders": getSafeNumber(client.activeWorkOrders),
        "Total Projects": getSafeNumber(client.totalProjects),
        "Total Candidates Required": getSafeNumber(client.totalCandidatesReq),
        "Total Candidates Hired": getSafeNumber(client.hired),
        "Candidates In Pipeline": getSafeNumber(client.staged),
        "Candidates Pending": getSafeNumber(client.pending),
        "Completion Rate (%)": calculatePercentage(
          getSafeNumber(client.hired),
          getSafeNumber(client.totalCandidatesReq)
        ),
        "Pipeline Fill Rate (%)": calculatePercentage(
          getSafeNumber(client.staged),
          getSafeNumber(client.totalCandidatesReq)
        ),
      }));

      const clientSheet = XLSX.utils.json_to_sheet(clientSummaryData);
      clientSheet["!cols"] = [
        { wch: 25 }, { wch: 15 }, { wch: 15 }, { wch: 15 }, { wch: 20 },
        { wch: 20 }, { wch: 20 }, { wch: 18 }, { wch: 18 }, { wch: 18 }
      ];
      XLSX.utils.book_append_sheet(workbook, clientSheet, "Client Summary");
    }

    // ==================== SHEET 4: PROJECT SUMMARY (DETAILED) ====================
    if (filteredData?.hoverData?.projectSummary?.length > 0) {
      const projectSummaryData = filteredData.hoverData.projectSummary.map((project) => ({
        "Project Name": project.projectName || "N/A",
        "Client Name": project.clientName || "N/A",
        "Total Work Orders": getSafeNumber(project.totalWorkOrders),
        "Active Work Orders": getSafeNumber(project.activeWorkOrders),
        "Total Candidates Required": getSafeNumber(project.totalCandidatesReq),
        "Total Candidates Hired": getSafeNumber(project.hired),
        "Candidates In Pipeline": getSafeNumber(project.staged),
        "Candidates Pending": getSafeNumber(project.pending),
        "Completion Rate (%)": calculatePercentage(
          getSafeNumber(project.hired),
          getSafeNumber(project.totalCandidatesReq)
        ),
        "Pipeline Fill Rate (%)": calculatePercentage(
          getSafeNumber(project.staged),
          getSafeNumber(project.totalCandidatesReq)
        ),
      }));

      const projectSheet = XLSX.utils.json_to_sheet(projectSummaryData);
      projectSheet["!cols"] = [
        { wch: 25 }, { wch: 25 }, { wch: 15 }, { wch: 15 }, { wch: 20 },
        { wch: 20 }, { wch: 20 }, { wch: 18 }, { wch: 18 }, { wch: 18 }
      ];
      XLSX.utils.book_append_sheet(workbook, projectSheet, "Project Summary");
    }

    // ==================== SHEET 5: ACTIVE WORK ORDERS SUMMARY ====================
    if (filteredData?.hoverData?.activeWOSummary?.length > 0) {
      const activeWOSummaryData = filteredData.hoverData.activeWOSummary.map((wo) => ({
        "Work Order Name": wo.woName || "N/A",
        "Work Order ID": wo.woId || "N/A",
        "Client Name": wo.clientName || "N/A",
        "Project Name": wo.projectName || "N/A",
        "Total Candidates Required": getSafeNumber(wo.totalCandidatesReq),
        "Hired": getSafeNumber(wo.hired),
        "In Pipeline": getSafeNumber(wo.staged),
        "Pending": getSafeNumber(wo.pending),
        "Completion Rate (%)": calculatePercentage(
          getSafeNumber(wo.hired),
          getSafeNumber(wo.totalCandidatesReq)
        ),
        "Pipeline Fill Rate (%)": calculatePercentage(
          getSafeNumber(wo.staged),
          getSafeNumber(wo.totalCandidatesReq)
        ),
        "Remaining Candidates": getSafeNumber(wo.totalCandidatesReq) - getSafeNumber(wo.hired),
      }));

      const activeWOSheet = XLSX.utils.json_to_sheet(activeWOSummaryData);
      activeWOSheet["!cols"] = [
        { wch: 30 }, { wch: 15 }, { wch: 25 }, { wch: 25 }, { wch: 20 },
        { wch: 12 }, { wch: 15 }, { wch: 12 }, { wch: 18 }, { wch: 18 }, { wch: 20 }
      ];
      XLSX.utils.book_append_sheet(workbook, activeWOSheet, "Active WOs Summary");
    }

    // ==================== SHEET 6: EXPIRING WORK ORDERS ====================
    if (filteredData?.hoverData?.expiringWOs?.length > 0) {
      const expiringWOsData = filteredData.hoverData.expiringWOs.map((wo) => {
        const deadlineDate = wo.deadlineDate ? dayjs(wo.deadlineDate) : null;
        const daysUntilDeadline = deadlineDate ? deadlineDate.diff(dayjs(), "days") : null;
        
        return {
          "Work Order Name": wo.woName || "N/A",
          "Work Order ID": wo.woId || "N/A",
          "Client Name": wo.clientName || "N/A",
          "Project Name": wo.projectName || "N/A",
          "Deadline Date": formatDateOnly(wo.deadlineDate),
          "Days Until Deadline": daysUntilDeadline !== null ? daysUntilDeadline : "N/A",
          "Total Candidates Required": getSafeNumber(wo.totalCandidatesReq),
          "Hired": getSafeNumber(wo.hired),
          "In Pipeline": getSafeNumber(wo.staged),
          "Pending": getSafeNumber(wo.pending),
          "Completion Rate (%)": calculatePercentage(
            getSafeNumber(wo.hired),
            getSafeNumber(wo.totalCandidatesReq)
          ),
          "Urgency": daysUntilDeadline !== null && daysUntilDeadline <= 7 ? "High" : 
                    daysUntilDeadline !== null && daysUntilDeadline <= 15 ? "Medium" : "Low",
        };
      });

      const expiringWOSheet = XLSX.utils.json_to_sheet(expiringWOsData);
      expiringWOSheet["!cols"] = [
        { wch: 30 }, { wch: 15 }, { wch: 25 }, { wch: 25 }, { wch: 15 },
        { wch: 18 }, { wch: 20 }, { wch: 12 }, { wch: 15 }, { wch: 12 }, { wch: 18 }, { wch: 12 }
      ];
      XLSX.utils.book_append_sheet(workbook, expiringWOSheet, "Expiring WOs");
    }

    // ==================== SHEET 7: WORK ORDERS ON PRIORITY ====================
    if (filteredData?.hoverData?.wosOnPriority?.length > 0) {
      const priorityWOsData = filteredData.hoverData.wosOnPriority.map((wo) => ({
        "Work Order Name": wo.woName || "N/A",
        "Work Order ID": wo.woId || "N/A",
        "Client Name": wo.clientName || "N/A",
        "Project Name": wo.projectName || "N/A",
        "Priority Level": wo.priority || "N/A",
        "Total Candidates Required": getSafeNumber(wo.totalCandidatesReq),
        "Hired": getSafeNumber(wo.hired),
        "In Pipeline": getSafeNumber(wo.staged),
        "Pending": getSafeNumber(wo.pending),
        "Completion Rate (%)": calculatePercentage(
          getSafeNumber(wo.hired),
          getSafeNumber(wo.totalCandidatesReq)
        ),
        "Remaining Candidates": getSafeNumber(wo.totalCandidatesReq) - getSafeNumber(wo.hired),
      }));

      const priorityWOSheet = XLSX.utils.json_to_sheet(priorityWOsData);
      priorityWOSheet["!cols"] = [
        { wch: 30 }, { wch: 15 }, { wch: 25 }, { wch: 25 }, { wch: 15 },
        { wch: 20 }, { wch: 12 }, { wch: 15 }, { wch: 12 }, { wch: 18 }, { wch: 20 }
      ];
      XLSX.utils.book_append_sheet(workbook, priorityWOSheet, "Priority WOs");
    }

    // ==================== SHEET 8: APPLICATION STATUS BREAKDOWN ====================
    if (filteredData?.applicationStatusData?.length > 0) {
      const totalApplications = filteredData.applicationStatusData.reduce(
        (sum, status) => sum + getSafeNumber(status.count),
        0
      );

      const applicationStatusData = filteredData.applicationStatusData.map((status) => {
        const count = getSafeNumber(status.count);
        return {
          "Status": status.status || "N/A",
          "Count": count,
          "Percentage of Total": calculatePercentage(count, totalApplications),
        };
      });

      // Add total row
      applicationStatusData.push({
        "Status": "TOTAL",
        "Count": totalApplications,
        "Percentage of Total": 100,
      });

      const applicationStatusSheet = XLSX.utils.json_to_sheet(applicationStatusData);
      applicationStatusSheet["!cols"] = [
        { wch: 25 }, { wch: 15 }, { wch: 20 }
      ];
      XLSX.utils.book_append_sheet(workbook, applicationStatusSheet, "Application Status");
    }

    // ==================== SHEET 9: USER STATISTICS (if available) ====================
    if (data?.roleCounts?.length > 0) {
      const totalUsers = data.roleCounts.reduce((sum, role) => sum + getSafeNumber(role.count), 0);
      
      const userStatsData = data.roleCounts.map((role) => ({
        "Role": role._id?.charAt(0).toUpperCase() + role._id?.slice(1) || "N/A",
        "Count": getSafeNumber(role.count),
        "Percentage of Total": calculatePercentage(getSafeNumber(role.count), totalUsers),
      }));

      // Add total row
      userStatsData.push({
        "Role": "TOTAL",
        "Count": totalUsers,
        "Percentage of Total": 100,
      });

      const userStatsSheet = XLSX.utils.json_to_sheet(userStatsData);
      userStatsSheet["!cols"] = [
        { wch: 25 }, { wch: 15 }, { wch: 20 }
      ];
      XLSX.utils.book_append_sheet(workbook, userStatsSheet, "User Statistics");
    }

    // ==================== SHEET 10: KPI DETAILED ANALYSIS ====================
    const kpiAnalysisData = [
      ["KPI METRIC", "VALUE", "TARGET", "STATUS"],
      ["Time to Hire (days)", getSafeNumber(filteredData?.kpis?.timeToHire), "≤ 30", 
        getSafeNumber(filteredData?.kpis?.timeToHire) <= 30 ? "✓ On Target" : "⚠ Needs Improvement"],
      ["Average Time in Pipeline (days)", getSafeNumber(filteredData?.kpis?.averageTimeInPipeline), "≤ 45",
        getSafeNumber(filteredData?.kpis?.averageTimeInPipeline) <= 45 ? "✓ On Target" : "⚠ Needs Improvement"],
      ["Offer Acceptance Rate (%)", getSafeNumber(filteredData?.kpis?.offerAcceptanceRate), "≥ 80",
        getSafeNumber(filteredData?.kpis?.offerAcceptanceRate) >= 80 ? "✓ On Target" : "⚠ Needs Improvement"],
      ["WO Pipeline Completion Rate (%)", getSafeNumber(filteredData?.kpis?.woPipelineCompletionRate), "≥ 70",
        getSafeNumber(filteredData?.kpis?.woPipelineCompletionRate) >= 70 ? "✓ On Target" : "⚠ Needs Improvement"],
      ["WO Completion Rate (%)", getSafeNumber(filteredData?.kpis?.woCompletionRate), "≥ 85",
        getSafeNumber(filteredData?.kpis?.woCompletionRate) >= 85 ? "✓ On Target" : "⚠ Needs Improvement"],
    ];

    const kpiSheet = XLSX.utils.aoa_to_sheet(kpiAnalysisData);
    kpiSheet["!cols"] = [
      { wch: 35 }, { wch: 15 }, { wch: 15 }, { wch: 20 }
    ];
    XLSX.utils.book_append_sheet(workbook, kpiSheet, "KPI Analysis");

    // ==================== EXPORT FILE ====================
    const filename = `Admin_Dashboard_Detailed_Report_${dayjs().format("YYYYMMDD_HHmmss")}.xlsx`;
    XLSX.writeFile(workbook, filename);
    message.success("Detailed dashboard report exported successfully!");
  } catch (error) {
    console.error("Error exporting to Excel:", error);
    message.error("Failed to export data. Please try again.");
  }
};
